export const API_ENDPOINTS = {
  ADMIN: {
    TEACHERS: '/teacher',
    TEACHER_BY_ID: (id: string) => `/teacher/${id}`,
    TEACHER_CLASSES: (teacherId: string) => `/teacher/${teacherId}/classes`,
    STUDENTS: '/student',
    STUDENT_BY_ID: (id: string) => `/student/${id}`,
    CLASSES: '/class/class-dtls',
  },
  SCHOOL: {
    BY_ID: (id: string) => `/school/${id}`,
    PROFILE_IMAGE: (id: string) => `/school/${id}/profile-image`,
    OWNER_PROFILE_IMAGE: (id: string) => `/school/${id}/owner-profile-image`,
    CLASSES: '/school/classes',
    FETCH_CLASSES: '/school/fetch/classes',
    SECTIONS: '/school/sections',
    FETCH_SECTIONS: '/school/fetch/sections',
    SECTION_UPDATE: (id: number) => `/school/sections/${id}`,
    SECTION_DELETE: (id: number) => `/school/sections/${id}`,
    CLASS_UPDATE: (id: number) => `/school/classes/${id}`,
    CLASS_DELETE: (id: number) => `/school/classes/${id}`,
    CLASS_TEACHERS: '/school/class-teachers',
  },
  ADMINISTRATOR: {
    LIST: '/administrator',
    BY_ID: (id: string) => `/administrator/${id}`,
    PROFILE_IMAGE: (id: string) => `/administrator/${id}/profile-image`,
  },
  TEACHER: {
    LIST: '/teacher',
    REGISTER: '/teacher/register',
    BY_ID: (id: string) => `/teacher/${id}`,
    DETAILS: (id: string) => `/teacher/${id}/details`,
    PROFILE_IMAGE: (id: string) => `/teacher/${id}/profile-image`,
    ADDRESS_ADD: (id: string) => `/teacher/${id}/address`,
    ADDRESS_UPDATE: (addressId: number) => `/teacher/address/${addressId}`,
    ADDRESS_DELETE: (addressId: number) => `/teacher/address/${addressId}`,
    CLASS_ADD: (id: string) => `/teacher/${id}/class`,
    CLASS_UPDATE: (classId: number) => `/teacher/class/${classId}`,
    CLASS_DELETE: (classId: number) => `/teacher/class/${classId}`,
    SCHOOL_RECORD: (recordId: number) => `/teacher/school-record/${recordId}`,
    ADD_CLASS_TEACHER: '/teacher/add-class-teacher',
    REMOVE_CLASS_TEACHER: '/teacher/remove-class-teacher',
    COORDINATOR_CLASS: '/teacher/coordinator-class',
    COORDINATOR_CLASS_DELETE: (mappingId: number) => `/teacher/coordinator-class/${mappingId}`,
  },
  CLASS: {
    // GET & POST both use the same base path (no /fetch/ prefix)
    CLASS_DTLS: '/class/class-dtls',
    CLASS_DTLS_BY_ID: (id: number) => `/class/class-dtls/${id}`,
    SUBJECT_DTLS: '/class/subject-dtls',
    SUBJECT_DTLS_BY_ID: (id: number) => `/class/subject-dtls/${id}`,
    CLASS_SUBJECT_DTLS: '/class/class-subject-dtls',
    CLASS_SUBJECT_DTLS_BY_ID: (id: number) => `/class/class-subject-dtls/${id}`,
    PERIOD_SLOTS: '/class/period-slots',
    PERIOD_SLOTS_BY_ID: (id: number) => `/class/period-slots/${id}`,
    TIMETABLE: '/class/timetable',
    TIMETABLE_BY_ID: (id: number | string) => `/class/timetable/${id}`,
    TIMETABLE_FETCH: '/class/timetable/fetch',
  },
  STUDENT: {
    LIST: '/student',
    REGISTER: '/student/register',
    BY_ID: (id: string) => `/student/details/${id}`,
    DETAILS: (id: string) => `/student/${id}/details`,
    STATUS: (id: string) => `/student/${id}/status`,
    PROFILE_IMAGE: (id: string) => `/student/${id}/profile-image`,
    BASIC_DETAILS: '/student/basic-details',
    ACADEMIC_ADD: (studentId: string) => `/student/${studentId}/academic`,
    ACADEMIC_UPDATE: (academicId: number) => `/student/academic/${academicId}`,
    PARENT_ADD: (studentId: string) => `/student/${studentId}/parent`,
    PARENT_UPDATE: (parentId: number) => `/student/parent/${parentId}`,
    PARENT_DELETE: (parentId: number) => `/student/parent/${parentId}`,
    MEDICAL_ADD: (studentId: string) => `/student/${studentId}/medical`,
    MEDICAL_UPDATE: (medicalId: number) => `/student/medical/${medicalId}`,
    MEDICAL_DELETE: (medicalId: number) => `/student/medical/${medicalId}`,
    ADDRESS_ADD: (studentId: string) => `/student/${studentId}/address`,
    ADDRESS_UPDATE: (addressId: number) => `/student/address/${addressId}`,
    ADDRESS_DELETE: (addressId: number) => `/student/address/${addressId}`,
    ATTENDANCE_BULK: '/student/attendance/bulk',
    ATTENDANCE_UPDATE: (recordId: number) => `/student/attendance/${recordId}`,
    ATTENDANCE_FILTER: '/student/attendance/filter',
    BIRTHDAYS: '/student/birthdays',
  },
  COORDINATOR: {
    DASHBOARD_SUMMARY: '/coordinator/dashboard-summary',
  },
  PRINCIPAL: {
    DASHBOARD_SUMMARY: '/principal/dashboard-summary',
  },
  ACADEMIC: {
    SUBJECT_CHAPTER: '/academic/subject-chapter',
    SUBJECT_CHAPTER_BY_ID: (id: number) => `/academic/subject-chapter/${id}`,
    SUBJECT_TOPIC: '/academic/subject-topic',
    SUBJECT_TOPIC_BY_ID: (id: number) => `/academic/subject-topic/${id}`,
    SUBJECT_PROGRESS: '/academic/subject-progress',
    CHAPTER_PROGRESS: '/academic/chapter-progress',
    TEACHING_PROGRESS: '/academic/teaching-progress',
    TEACHING_PROGRESS_BY_ID: (id: number) => `/academic/teaching-progress/${id}`,
    HOMEWORK: '/academic/homework',
    HOMEWORK_BY_ID: (id: number) => `/academic/homework/${id}`,
    HOMEWORK_ATTACHMENT: '/academic/homework-attachment',
    HOMEWORK_ATTACHMENT_BY_ID: (id: number) => `/academic/homework-attachment/${id}`,
    HOMEWORK_DOCUMENT: '/academic/homework-document',
    HOMEWORK_DOCUMENT_BY_HW_ID: (hwId: number) => `/academic/homework-document/${hwId}`,
    HOMEWORK_DOCUMENT_BY_ID: (id: number) => `/academic/homework-document/${id}`,
    STUDY_MATERIAL: '/academic/study-material',
    STUDY_MATERIAL_BY_ID: (id: number) => `/academic/study-material/${id}`,
    HOMEWORK_SUBMISSION: '/academic/homework-submission',
    HOMEWORK_SUBMISSION_BY_HW_ID: (hwId: number) => `/academic/homework-submission/${hwId}`,
    HOMEWORK_SUBMISSION_BY_ID: (id: number) => `/academic/homework-submission/${id}`,
    CLASSWORK: '/academic/classwork',
    CLASSWORK_BY_ID: (id: number) => `/academic/classwork/${id}`,
    EXAM: '/academic/exam',
    EXAM_BY_ID: (id: number) => `/academic/exam/${id}`,
    EXAM_SCHEDULE: '/academic/exam-schedule',
    EXAM_SCHEDULE_BY_ID: (id: number) => `/academic/exam-schedule/${id}`,
    EXAM_RESULT: '/academic/exam-result',
    EXAM_RESULT_BY_ID: (id: number) => `/academic/exam-result/${id}`,
  },
  EXAMINATION: {
    // Master
    EXAM: '/examination/exam',
    EXAM_BY_ID: (id: number) => `/examination/exam/${id}`,
    EXAMS: '/examination/exams',
    EXAM_SUBJECT: '/examination/exam-subject',
    EXAM_SUBJECT_BY_ID: (id: number) => `/examination/exam-subject/${id}`,
    EXAM_SUBJECTS: '/examination/exam-subjects',
    GRADE_CONFIG: '/examination/grade-config',
    GRADE_CONFIG_BY_ID: (id: number) => `/examination/grade-config/${id}`,
    EXAM_TYPE: '/examination/exam-type',
    EXAM_TYPE_BY_ID: (id: number) => `/examination/exam-type/${id}`,
    EXAM_TYPES: '/examination/exam-types',
    // Schedule
    SCHEDULE: '/examination/schedule',
    SCHEDULE_BY_ID: (id: number) => `/examination/schedule/${id}`,
    SCHEDULE_STUDENT: '/examination/schedule/student',
    // Marks
    MARKS: '/examination/marks',
    MARKS_BY_ID: (id: number) => `/examination/marks/${id}`,
    MARKS_BULK_ABSENT: '/examination/marks/bulk/absent',
    MARKS_LOCK: '/examination/marks/lock',
    MARKS_UNLOCK: '/examination/marks/unlock',
    MARKS_COMPLETION: '/examination/marks/completion-status',
    MARKS_STUDENT: (studentId: string) => `/examination/marks/student/${studentId}`,
    // Results
    RESULT_GENERATE: '/examination/result/generate',
    RESULT_CLASS: '/examination/result/class',
    RESULT_TEACHER_REMARKS: (id: number) => `/examination/result/remarks/teacher/${id}`,
    RESULT_PRINCIPAL_REMARKS: (id: number) => `/examination/result/remarks/principal/${id}`,
    RESULT_PUBLISH: '/examination/result/publish',
    RESULT_UNPUBLISH: '/examination/result/unpublish',
    RESULT_REPORT_CARD: (studentId: string) => `/examination/result/report-card/${studentId}`,
    // Analytics
    ANALYTICS_STUDENT: (studentId: string) => `/examination/analytics/student-performance/${studentId}`,
    ANALYTICS_CLASS: '/examination/analytics/class-overview',
    ANALYTICS_SUBJECT: '/examination/analytics/subject-analysis',
    ANALYTICS_TOPPERS: '/examination/analytics/toppers',
  },
  ANNOUNCEMENT: {
    BASE: '/announcement',
    BY_ID: (id: number) => `/announcement/${id}`,
    ATTACHMENT: (id: number) => `/announcement/attachment/${id}`,
    REMOVE_ATTACHMENT: (attachmentId: number) => `/announcement/attachment/${attachmentId}`,
    TOGGLE_PIN: (id: number) => `/announcement/${id}/pin`,
    READ_RECEIPTS: (id: number) => `/announcement/${id}/read-receipts`,
  },
  EVENT: {
    BASE: '/event',
    BY_ID: (id: number) => `/event/${id}`,
    CALENDAR: '/event/calendar',
    UPCOMING: '/event/upcoming',
    HOLIDAYS: '/event/holidays',
  },
  EVENT_TYPE: {
    BASE: '/event-type',
    BY_ID: (id: number) => `/event-type/${id}`,
  },
  TEACHER_LEAVE: {
    BASE: '/teacher-leave',
    BY_ID: (id: number) => `/teacher-leave/${id}`,
    APPROVE: (id: number) => `/teacher-leave/${id}/approve`,
    REJECT: (id: number) => `/teacher-leave/${id}/reject`,
    CANCEL: (id: number) => `/teacher-leave/${id}/cancel`,
    REVOKE: (id: number) => `/teacher-leave/${id}/revoke`,
    BALANCE: '/teacher-leave/balance',
    BALANCE_INITIALIZE: '/teacher-leave/balance/initialize',
  },
  SUBSTITUTE_PERIOD: {
    BASE: '/substitute-period',
    AVAILABLE_TEACHERS: '/substitute-period/available-teachers',
    ASSIGN: (id: number) => `/substitute-period/${id}/assign`,
  },
  TEACHER_ATTENDANCE: {
    BASE: '/teacher-attendance',
    MARK: '/teacher-attendance/mark',
    DAY: '/teacher-attendance/day',
  },
} as const;
