export const API_ENDPOINTS = {
  ADMIN: {
    TEACHERS: '/teacher',
    TEACHER_BY_ID: (id: string) => `/teacher/${id}`,
    TEACHER_CLASSES: (teacherId: string) => `/teacher/${teacherId}/classes`,
    STUDENTS: '/student',
    STUDENT_BY_ID: (id: string) => `/student/${id}`,
    CLASSES: '/class/class-dtls',
  },
  SCHOOL: {
    BY_ID: (id: string) => `/school/${id}`,
    PROFILE_IMAGE: (id: string) => `/school/${id}/profile-image`,
    OWNER_PROFILE_IMAGE: (id: string) => `/school/${id}/owner-profile-image`,
    CLASSES_DETAILS: '/school/classes/details',
    CLASSES: '/school/classes',
    CLASS_ADD: '/school/class/add',
    CLASS_UPDATE: (classDtlsId: number) => `/school/class/update/${classDtlsId}`,
    CLASS_DELETE: (classDtlsId: number) => `/school/class/${classDtlsId}`,
    CLASS_SECTIONS: (className: string) => `/school/classes/${encodeURIComponent(className)}/sections`,
    CLASS_TEACHERS: '/school/class-teachers',
  },
  ADMINISTRATOR: {
    LIST: '/administrator',
    BY_ID: (id: string) => `/administrator/${id}`,
    PROFILE_IMAGE: (id: string) => `/administrator/${id}/profile-image`,
  },
  TEACHER: {
    LIST: '/teacher',
    REGISTER: '/teacher/register',
    BY_ID: (id: string) => `/teacher/${id}`,
    DETAILS: (id: string) => `/teacher/${id}/details`,
    PROFILE_IMAGE: (id: string) => `/teacher/${id}/profile-image`,
    ADDRESS_ADD: (id: string) => `/teacher/${id}/address`,
    ADDRESS_UPDATE: (addressId: number) => `/teacher/address/${addressId}`,
    ADDRESS_DELETE: (addressId: number) => `/teacher/address/${addressId}`,
    CLASS_ADD: (id: string) => `/teacher/${id}/class`,
    CLASS_UPDATE: (classId: number) => `/teacher/class/${classId}`,
    CLASS_DELETE: (classId: number) => `/teacher/class/${classId}`,
    SCHOOL_RECORD: (recordId: number) => `/teacher/school-record/${recordId}`,
    ADD_CLASS_TEACHER: '/teacher/add-class-teacher',
    REMOVE_CLASS_TEACHER: '/teacher/remove-class-teacher',
    COORDINATOR_CLASS: '/teacher/coordinator-class',
    COORDINATOR_CLASS_DELETE: (mappingId: number) => `/teacher/coordinator-class/${mappingId}`,
  },
  CLASS: {
    CLASS_DTLS: '/class/class-dtls',
    CLASS_DTLS_BY_ID: (id: number) => `/class/class-dtls/${id}`,
    CLASSES: '/class/classes',
    SECTIONS: '/class/sections',
    COMBINATIONS: '/class/combinations',
    CLASS_SECTION_LISTS: '/class/class-section-lists',
    SUBJECT_OPTIONS: '/class/subject-options',
    SUBJECT_OPTIONS_BY_ID: (id: number) => `/class/subject-options/${id}`,
    SUBJECT_DTLS: '/class/subject-dtls',
    SUBJECT_DTLS_BY_ID: (id: number) => `/class/subject-dtls/${id}`,
    PERIOD_SLOTS: '/class/period-slots',
    PERIOD_SLOTS_BY_ID: (id: number) => `/class/period-slots/${id}`,
    TIMETABLE: '/class/timetable',
    TIMETABLE_BY_ID: (id: number) => `/class/timetable/${id}`,
    TIMETABLE_FETCH: '/class/timetable/fetch',
  },
  STUDENT: {
    LIST: '/student',
    REGISTER: '/student/register',
    BY_ID: (id: string) => `/student/${id}`,
    DETAILS: (id: string) => `/student/${id}/details`,
    STATUS: (id: string) => `/student/${id}/status`,
    PROFILE_IMAGE: (id: string) => `/student/${id}/profile-image`,
    ACADEMIC_ADD: (studentId: string) => `/student/${studentId}/academic`,
    ACADEMIC_UPDATE: (academicId: number) => `/student/academic/${academicId}`,
    PARENT_ADD: (studentId: string) => `/student/${studentId}/parent`,
    PARENT_UPDATE: (parentId: number) => `/student/parent/${parentId}`,
    PARENT_DELETE: (parentId: number) => `/student/parent/${parentId}`,
    MEDICAL_ADD: (studentId: string) => `/student/${studentId}/medical`,
    MEDICAL_UPDATE: (medicalId: number) => `/student/medical/${medicalId}`,
    MEDICAL_DELETE: (medicalId: number) => `/student/medical/${medicalId}`,
    ADDRESS_ADD: (studentId: string) => `/student/${studentId}/address`,
    ADDRESS_UPDATE: (addressId: number) => `/student/address/${addressId}`,
    ADDRESS_DELETE: (addressId: number) => `/student/address/${addressId}`,
    ATTENDANCE_BULK: '/student/attendance/bulk',
    ATTENDANCE_UPDATE: (recordId: number) => `/student/attendance/${recordId}`,
    ATTENDANCE_FILTER: '/student/attendance/filter',
  },
  COORDINATOR: {
    DASHBOARD_SUMMARY: '/coordinator/dashboard-summary',
  },
  PRINCIPAL: {
    DASHBOARD_SUMMARY: '/principal/dashboard-summary',
  },
  ACADEMIC: {
    SUBJECT_CHAPTER: '/academic/subject-chapter',
    SUBJECT_CHAPTER_BY_ID: (id: number) => `/academic/subject-chapter/${id}`,
    SUBJECT_TOPIC: '/academic/subject-topic',
    SUBJECT_TOPIC_BY_ID: (id: number) => `/academic/subject-topic/${id}`,
    TEACHING_PROGRESS: '/academic/teaching-progress',
    TEACHING_PROGRESS_BY_ID: (id: number) => `/academic/teaching-progress/${id}`,
    HOMEWORK: '/academic/homework',
    HOMEWORK_BY_ID: (id: number) => `/academic/homework/${id}`,
    HOMEWORK_DOCUMENT: '/academic/homework-document',
    HOMEWORK_DOCUMENT_BY_HW_ID: (hwId: number) => `/academic/homework-document/${hwId}`,
    HOMEWORK_DOCUMENT_BY_ID: (id: number) => `/academic/homework-document/${id}`,
    HOMEWORK_SUBMISSION: '/academic/homework-submission',
    HOMEWORK_SUBMISSION_BY_HW_ID: (hwId: number) => `/academic/homework-submission/${hwId}`,
    HOMEWORK_SUBMISSION_BY_ID: (id: number) => `/academic/homework-submission/${id}`,
    CLASSWORK: '/academic/classwork',
    CLASSWORK_BY_ID: (id: number) => `/academic/classwork/${id}`,
    STUDY_MATERIAL: '/academic/teacher-study-material',
    STUDY_MATERIAL_BY_ID: (id: number) => `/academic/teacher-study-material/${id}`,
  },
} as const;
